# Use root/example as user/password credentials
version: '3.1'

services:

   checkup_web:
    image: checkup_web
#    build: .
    container_name: checkup_web

    restart: on-failure
    command: ["gunicorn", "run:app", "-b", "0.0.0.0:5000", "--reload"]
    ports:
      - 8090:5000
    networks:
      - app-network
#
##Docker Networks
networks:
  app-network:
